<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: mapsadmin
 * Date: Sun, 28 Apr 2019 23:56:31 +0000
 */

$conf['title'] = 'TU Maps';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['plugin']['authpdo']['debug'] = 1;
$conf['plugin']['authpdo']['dsn'] = 'mysql:host=localhost;dbname=wiki_data;charset=utf8';
$conf['plugin']['authpdo']['user'] = 'root';
$conf['plugin']['authpdo']['pass'] = 'TempleOwls2020';
$conf['plugin']['authpdo']['select-user'] = 'SELECT username    AS "user",
       fullName    AS "name",
       password    AS "hash",
       email       AS "mail",
       id          AS "uid"
  FROM user
  WHERE username = :user
';
$conf['plugin']['authpdo']['select-user-groups'] = 'SELECT `groupName` AS "group"
  FROM `member` AS m,
       `groups`  AS g
 WHERE m.`gid` = g.`id`
   AND m.`uid` = :uid
';
$conf['plugin']['authpdo']['select-groups'] = 'SELECT id        AS "gid", 
       groupName AS "group"
    FROM `groups`
';
$conf['plugin']['authpdo']['insert-user'] = 'INSERT INTO `user`(`username`, `password`, `fullName`, `email`, `userIcon`)
    VALUES (:user, :hash, :name, :mail, \'\')
';
$conf['plugin']['authpdo']['delete-user'] = 'DELETE FROM `user` WHERE id = :uid
';
$conf['plugin']['authpdo']['list-users'] = 'SELECT DISTINCT username AS "user"
    FROM `user`   AS U,
         `member` AS M,
         `groups`  AS G
   WHERE U.id  = M.uid
     AND M.gid = G.id
     AND G.groupName LIKE :group
     AND U.username LIKE :user
     AND U.fullName  LIKE :name
     AND U.email  LIKE :mail
ORDER BY username
   LIMIT :start,:limit
';
$conf['plugin']['authpdo']['count-users'] = 'SELECT COUNT(DISTINCT username) AS "count"
  FROM `user`   AS U,
       `member` AS M,
       `groups`  AS G
 WHERE U.id  = M.uid
   AND M.gid = G.id
   AND G.groupName LIKE :group
   AND U.username LIKE :user
   AND U.fullName  LIKE :name
   AND U.email  LIKE :mail 
';
$conf['plugin']['authpdo']['update-user-info'] = 'UPDATE `user`
   SET fullName = :name,
       email = :mail
 WHERE id   = :uid
';
$conf['plugin']['authpdo']['update-user-login'] = 'UPDATE `user`
   SET username = :newlogin
 WHERE id    = :uid
';
$conf['plugin']['authpdo']['update-user-pass'] = 'UPDATE `user`
   SET password = :hash
 WHERE id   = :uid
';
$conf['plugin']['authpdo']['insert-group'] = 'INSERT INTO `groups` (`groupName`)
     VALUES (:group)
';
$conf['plugin']['authpdo']['join-group'] = 'INSERT INTO member (uid, gid)
     VALUES (:uid, :gid)
';
$conf['plugin']['authpdo']['leave-group'] = 'DELETE FROM `member`
      WHERE uid = :uid
        AND gid = :gid
';

// end auto-generated content
